security_policies = [
    {
        "name": "Users to Internal DNS Server",
        "type": "universal",
        "description": "Allows user LANs to communicate with internal DNS server",
        "tag": ["Internet Gateway"],
        "fromzone": ["User LAN"],
        "source": ["All User Subnets"],
        "tozone": ["Datacenter"],
        "destination": ["Datacenter Internal DNS"],
        "application": ["dns", "icmp", "ping"],
        "action": "allow",
        "log_end": True,
    },
    {
        "name": "Users to Internal DNS Server",
        "type": "universal",
        "description": "Allows user LANs to communicate with internal DNS server",
        "tag": ["Internet Gateway"],
        "fromzone": ["User LAN"],
        "source": ["All User Subnets"],
        "tozone": ["Datacenter"],
        "destination": ["Datacenter Internal DNS"],
        "application": ["dns", "icmp", "ping"],
        "action": "allow",
        "log_end": True,
    },
    {
        "name": "Internal DNS to Internet",
        "type": "universal",
        "description": "Allows internal DNS to communicate with Internet",
        "fromzone": ["Datacenter"],
        "source": ["Datacenter Internal DNS"],
        "tozone": ["Outside"],
        "destination": ["any"],
        "application": ["dns", "icmp", "ping"],
        "action": "allow",
        "log_end": True,
    },
    {
        "name": "General Internet",
        "type": "universal",
        "description": "Allows users access to the Internet",
        "tag": ["Internet Gateway"],
        "fromzone": ["User LAN"],
        "source": ["All User Subnets"],
        "tozone": ["Outside"],
        "destination": ["any"],
        "application": ["web-browsing", "ssl", "icmp", "ping"],
        "action": "allow",
        "log_end": True,
    },
]
